### ISSUE TITLE
@vercel/blob - `put` Error: The Edge Function "api" is referencing unsupported modules: 

### ISSUE THREAD

**Issue by eztinkerdreams** [vercel/storage#440]
I am attempting to upload a `102k` file. I am using [solid-start](https://start.solidjs.com/getting-started/what-is-solidstart) with `SSR` This is an existing site that I have working with no-issues, I'm trying to add functionality.
I am using `"@vercel/blob": "^0.12.0",`

```
Error: The Edge Function "api" is referencing unsupported modules:
        - vercel/path0/dist/index.mjs: net, http, stream, querystring, stream/web, worker_threads, perf_hooks, util/types, tls, console, url, zlib, string_decoder, crypto, diagnostics_channel
```

![2023-10-25_11-57-40](https://github.com/vercel/storage/assets/7387907/5a7b039c-8d7a-4af3-b134-4b9cee89811f)

This works flawlessly locally with `npm run dev` which uses `solid-start dev`

If I add `import { put } from '@vercel/blob'`
And then add this line in my `createServerAction$` which runs on the server everything works as expected locally, but when I try to deploy to vercel I get the error displayed above.

```
  const [publishingImages, { Form: PublishProductImages }] = createServerAction$(async (formData) => {
    const fileDetails = await formData.get('file');
    const viewType = formData.get('viewType');
    const titleSlug = formData.get('titleSlug');
    const blobResults = await put(
      `product/title/${titleSlug}/images/viewType/${viewType}/${fileDetails.name}`, 
      fileDetails, 
      {
        access: 'public',
      }
    );
    console.info('blobResults', blobResults);
  });
```

If I remove this bit, it does allow me to deploy
```
    const blobResults = await put(
      `product/title/${titleSlug}/images/viewType/${viewType}/${fileDetails.name}`, 
      fileDetails, 
      {
        access: 'public',
      }
    );
```

If I alias `import { put as doIt } from '@vercel/blob';`
and then use `    await doIt('foo', 'bar', { access: 'public' });`
I get... this when I try to deploy, notice the change from `api` to `render`
```
Error: The Edge Function "render" is referencing unsupported modules:
        - vercel/path0/dist/index.mjs: net, http, stream, querystring, stream/web, worker_threads, perf_hooks, util/types, tls, console, url, zlib, string_decoder, crypto, diagnostics_channel
             
```

I am trying to use the SDK as described here. 
Any help would be appreciated.
https://vercel.com/docs/storage/vercel-blob/quickstart#create-a-server-upload-route

**Comment by correttojs** [comment]
hey @eztinkerdreams , I successfully deployed a `solid-start` version `0.2.26` example using this Blob snippet:
```
import { put } from "@vercel/blob";
import { createServerAction$ } from "solid-start/server";

export default function Upload() {
  const [uploadStatus, { Form }] = createServerAction$(
    async (formData: FormData, { request }) => {
      const fileDetails = (await formData.get("file")) as File;
      const viewType = formData.get("viewType");
      const titleSlug = formData.get("titleSlug");
      const blobResults = await put(
        `product/title/${titleSlug}/images/viewType/${viewType}/${fileDetails.name}`,
        fileDetails,
        {
          access: "public",
        }
      );
      console.info("blobResults", blobResults);
      return blobResults;
    }
  );

  return (
    <Form>
      <input type="file" name="file" />
      <input type="hidden" name="viewType" value="thumbnail" />
      <input type="hidden" name="titleSlug" value="harry-potter" />
      <button type="submit" disabled={uploadStatus.pending}>
        Upload
      </button>
      {uploadStatus.result && (
        <div>{uploadStatus.result.pathname} Uploaded</div>
      )}
    </Form>
  );
}
```

What version of `solid-start` are you using? There are some known issues which has been fixed recently, see https://github.com/vercel/next.js/discussions/45384 for more details

**Comment by eztinkerdreams** [comment]
@correttojs At first attempt this didn't solve my problem, although I will admit I was hopeful. I was a bit out of date on the dependencies. I have upgraded all of these and tried another deployment but I still run into this issue.

I will continue to try and resolve this issue thank you for your help. If you can think of anything else just let me know.
Since you were able to get this to work, it points to some issue on my end. 

Framework Preset is set to `SolidStart` and `ENABLE_VC_BUILD="1"

![2023-10-27_07-07-27](https://github.com/vercel/storage/assets/7387907/b9d14b7a-3d32-4114-bde3-1cab359b8c8a)

```
Error: The Edge Function "render" is referencing unsupported modules:
        - vercel/path0/dist/index.mjs: net, http, stream, querystring, stream/web, node:stream, worker_threads, perf_hooks, util/types, tls, console, url, zlib, string_decoder, diagnostics_channel
```

![image](https://github.com/vercel/storage/assets/7387907/19382edc-7836-4b54-8274-4c2ec2668838)

**Comment by correttojs** [comment]
if it helps, I generated the project using the `vercel init` CLI command and selecting the `solid-start` framework.
This generated the following package.json:
```
{
  "scripts": {
    "dev": "solid-start dev",
    "build": "solid-start build",
    "start": "solid-start start"
  },
  "type": "module",
  "private": true,
  "devDependencies": {
    "solid-start-vercel": "^0.2.26",
    "typescript": "^5.0.4",
    "vite": "^4.3.8"
  },
  "dependencies": {
    "@solidjs/meta": "^0.28.5",
    "@solidjs/router": "^0.8.2",
    "@vercel/blob": "^0.14.1",
    "solid-js": "^1.7.5",
    "solid-start": "^0.2.26",
    "undici": "^5.22.1"
  },
  "engines": {
    "node": "18.x"
  }
}
```

You may also check the content of the `vite.config.js` and `tsconfig.json`
```
import { defineConfig } from "vite";
import solid from "solid-start/vite";
import vercel from "solid-start-vercel";

export default defineConfig({
  plugins: [solid({ adapter: vercel() })],
});
```

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "target": "ESNext",
    "module": "ESNext",
    "moduleResolution": "node",
    "jsxImportSource": "solid-js",
    "jsx": "preserve",
    "types": ["vite/client"],
    "baseUrl": "./",
    "paths": {
      "~/*": ["./src/*"]
    }
  }
}
```

**Comment by eztinkerdreams** [comment]
@correttojs can you confirm it works fine for you with SSR enabled?

Update: I was able to create a new project using the `vercel init` command, get it deployed and confirm I can upload blobs with this code. So the issue is 100% something with my local build/project configuration. With a working example, I should be able to work out what the issue is. Couple of differences, I am using vite, because I started from another template. I have SSR enabled I've also got a couple different build logins/configuration plugins that I need to look into for the build process. I will update here once I can find out exactly what it is that is causing the issue.

**Comment by correttojs** [comment]
ok thanks, let us know if you need further support

**Comment by eztinkerdreams** [comment]
This is what is causing the issue. I was able to reproduce with the default projects results from `vercel init` 
And just to confirm I do have the `ENABLE_VC_BUILD=1` [configuration](https://npmtrends.com/solid-start-vercel) value set in both my local `.env` file as well as the vercel settings for the project

![2023-10-27_09-30-03](https://github.com/vercel/storage/assets/7387907/ec76327c-3cbe-400f-a4a5-1aff3ff58100)

**Comment by correttojs** [comment]
ok, that makes sense, the issue is the same as https://github.com/vercel/next.js/discussions/45384. I will check if there's anything we can do about it. Is `edge: false` a valid workaround for you in the meantime?

**Comment by eztinkerdreams** [comment]
@correttojs I have deployed `edge: false` and it does work for me, which is great. It does change the `Type` in the log to `Serverless Function` instead of `Edge Function`

Just to confirm, it should work just fine as a edge function right? Also, does making this change mean that all my application will not be using edge runtime? This particular server action I'm using is for an `/admin` route, so is there a way I could just change the setting for routes that are like `/admin` ? that would allow everything else to work using edge runtime?

**Comment by correttojs** [comment]
The adapter seems to only offer the option to opt-in or opt-out the edge functions entirely, you could split the repo into 2 Vercel projects eventually.

We will investigate the option to replace the `crypto` dependency by other solutions supported by edge functions

**Comment by vvo** [comment]
To complete @correttojs answer:

> Just to confirm, it should work just fine as a edge function right?

Yes, and at this point I think you should open an issue on https://github.com/solidjs/solid-start/ because "crypto" should be available in Vercel Edge functions, and if not maybe there's something to change on solid-start. And/or someone from solid will have a recommendation for you, let us know. Comment back and we can reopen this issue if necessary.

**Comment by eztinkerdreams** [comment]
@vvo What makes you think that this is an issue with `solid-start`? I have a few API endpoints that use the crypo library with no issue in this deployed, all is working on the edge. I'm only having this issue when I import and try to use the `@vercel/edge` `put` function?

**Comment by eztinkerdreams** [comment]
I posted in `solid-start`
Here is a bare bones example
[issue-440.zip](https://github.com/vercel/storage/files/13217161/issue-440.zip)
