### ISSUE TITLE
Creating a blob storage in the dashboard always fails with "An unexpected internal error occurred"

### ISSUE THREAD

**Issue by willemmulder** [vercel/storage#463]
Going to https://vercel.com/dashboard/stores and trying to create a blob store always fails.
The message I get is "An unexpected internal error occurred".
I'm on the Hobby plan.

Anyone else have the same issue?

**Comment by vvo** [comment]
Hey there @willemmulder, Vercel is currently experiencing an outage that is impacting your ability to create blob stores, I will update this ticket when this is resolved. And you can follow the incident status here: https://www.vercel-status.com/incidents/y3q60vnpczsc

**Comment by willemmulder** [comment]
Ah, I had checked that page but missed the incident due to the title not mentioning Blobs. So many systems not working today: Digital Ocean, Vercel, Cloudflare, SMS services... Hope things get resolved quickly. Thanks!

**Comment by daohoangson** [comment]
My blob storage has been created successfully but the `vercel-storage.com` subdomain is not resolving. Is this related to the outage?

The URLs look like this `https://wj9ntx636sodrfkz.public.blob.vercel-storage.com/foo/bar`

**Comment by vvo** [comment]
Hey there, we're digging this issue as we speak. We believe a few folks were able to create blob store during a time window where it was problematic. @daohoangson or @vntw can you try deleting your blob store and creating it again? Let us know if this is working.

**Comment by daohoangson** [comment]
Not working yet for this new blob store: `mumc6jh3x3iolqfl.public.blob.vercel-storage.com`.

**Comment by vntw** [comment]
Thanks for the info @vvo, unfortunately same result for me, created another blob (9cekvlwpforegb7y.public.blob.vercel-storage.com) with the same issue

**Comment by vvo** [comment]
Thanks to both of you, let's keep these badly created blob stores as they are while we're working on resolving this issue. Sorry for the inconvenience.

**Comment by vvo** [comment]
Hey there @vntw @willemmulder @daohoangson this is now solved. For now your best option is to delete your blob store and create it again, then it will work 100%.

We will be fixing all blob stores created during the incident one by one on Monday 9am EST otherwise. Thanks.

**Comment by daohoangson** [comment]
I can see that the new blob store is working (subdomain `1lcr94v1lgpvi6vs.public.blob.vercel-storage.com`). The old ones are still not resolving, I guess they will take a while.

**Comment by vvo** [comment]
Hey there, all blob stores are now fixed. Thanks for your patience

**Comment by ya2s** [comment]
@vvo 
I'm experiencing the same problem now
It doesn't seem to have occurred either

> No incidents reported today.


<img width="1058" height="822" alt="Image" src="https://github.com/user-attachments/assets/26aa99b3-6aab-445a-96ea-94eb5f7c9e88" />

**Comment by vvo** [comment]
@ya2s This is a different issue (not being able to upload in your case, this issue was about not being able to create a store), can you open a support ticket here: https://vercel.com/help? With these details:
- team id (available in your Vercel settings)
- store id (available in your store settings)
- any browser console errors
- if this is a recurring issue or not (i.e. can you reproduce it)

 If for some reason you can't open a ticket, just email me these details at vincent.voyer@vercel.com

Thanks!
