### ISSUE TITLE
Progress rate of upload to Blob

### ISSUE THREAD

**Issue by minodisk** [vercel/storage#543]
When uploading a file to a Blob, is there a way to get the progress rate of the upload?

**Comment by vvo** [comment]
Hey @minodisk, this is on our roadmap (no ETA), we were thinking of:

```ts
put('file.png', file, {
  onProgress(bytesSent: number, totalBytesToSend: number | undefined) // undefined when file is a stream
});
```

what do you think?

**Comment by minodisk** [comment]
That looks like a workable enough interface. I have high expectations!

**Comment by pie6k** [comment]
@minodisk it seems to be marked as completed, but I think I don't see such an API in the put method. I'm not sure if I am missing it somewhere

**Comment by xavimb** [comment]
The same issue has been highlighted here:
https://github.com/vercel/storage/issues/642

**Comment by Vitalii-Hurieiev** [comment]
Could you please provide an update on the status? Is it still in development?

**Comment by hcoretech** [comment]
Building a software store ,need help with onprogress with vercel blob, am using nextjs app router

**Comment by vvo** [comment]
Hey there, we just published a preview version of `@vercel/blob` which includes a way to track the progress of uploads.

If you want to try it, please upgrade to `@vercel/blob@0.26.0-a0c75211-20241025223154` in your package.json. Then use it this way:

```ts
// also works with upload()
const blob = await put('file.pdf', file, {
  onUploadProgress(event) {
    console.log(event.loaded, event.total, event.percentage);
  }
});
```

If you're using Next.js and getting errors about undici, please upgrade to at least `next@14.2.0` or force undici to be at version 5 in your package.json using pnpm overrides for example: https://pnpm.io/package_json#pnpmoverrides.

cc @hcoretech @Vitalii-Hurieiev @xavimb @pie6k @minodisk

**Comment by hcoretech** [comment]
Thanks @vvo i tried it but was still getting the undici error updated my nextjs and it updated to 15.0  but still getting the error ,check outy override if okay

{
   "Pnpm" :{

      overrides : {
   
     "foo" :  "@undici"

     }
   }
       
      Dependencies:{

"undici" : "^5.0.0"

}
}


Please help out

**Comment by vvo** [comment]
@hcoretech which error are you getting exactly? Thanks

**Comment by hcoretech** [comment]
Thanks @vvo saw my error i was using npm to install the update instead of pnpm ,notice it  made the change and it worked fine .

**Comment by hcoretech** [comment]
> @hcoretech which error are you getting exactly? Thanks
Am using upload nextjs I keep getting undici's proxy-authorizationheader not cleared on cross-origin redirect for dispatch,request stream ,pipeline

**Comment by vvo** [comment]
@hcoretech I just tested on a brand new Next.js website and this is working fine, you do not need the undici override. Undici override is only required if you use Next.js < 14.2.0.

Your error seems to be a different one: https://github.com/nodejs/undici/security/advisories/GHSA-m4v8-wqvr-p9f7

If you can create a brand new repository that is constantly showing this error please open a new issue, thanks!

**Comment by vvo** [comment]
This feature is now released in `@vercel/blob@26.0.0`, it's compatible with Node.js, browsers, client or server uploads, and most recent Next.js versions too.

**Comment by hcoretech** [comment]
My vercel/blob was refusing to update from v 23.4 to 26.0 Was getting that undici error,but when i deleted the package.json file 
 
 Then created new json file
 
   npm init
  Then install the latest vercel blob
 npm i @vercel/blob 
  And it did upgrade fine but i had to install each dependencies i used on it again.
 npm install 

Thanks @vvo

**Comment by vvo** [comment]
@hcoretech weird but happy this is working.

For everyone here, since this was a well followed ticket, I wanted to raise your awareness on an upcoming change we'd like to do on Vercel Blob SDK: no more random suffixes by default. Please join the conversation here:
https://x.com/vvoyer/status/1854816275173634175

🙏
